# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miuicamera-sapphire/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/miuicamera-sapphire


PRODUCT_PACKAGES += \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libmicampostproc_client \
    vendor.xiaomi.hardware.campostproc@1.0-system \
    ExtraPhotoGlobal \
    MiuiCamera
